// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Imtiaz246/Thesis-Management-System/internal/handler"
	"github.com/Imtiaz246/Thesis-Management-System/internal/repository"
	"github.com/Imtiaz246/Thesis-Management-System/internal/server"
	"github.com/Imtiaz246/Thesis-Management-System/internal/service"
	"github.com/Imtiaz246/Thesis-Management-System/internal/service/batch"
	"github.com/Imtiaz246/Thesis-Management-System/internal/service/team"
	"github.com/Imtiaz246/Thesis-Management-System/internal/service/user"
	"github.com/Imtiaz246/Thesis-Management-System/pkg/app"
	"github.com/Imtiaz246/Thesis-Management-System/pkg/helper/sid"
	"github.com/Imtiaz246/Thesis-Management-System/pkg/log"
	"github.com/Imtiaz246/Thesis-Management-System/pkg/mailer"
	"github.com/Imtiaz246/Thesis-Management-System/pkg/server/http"
	"github.com/Imtiaz246/Thesis-Management-System/pkg/token"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwt := token.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(db, client, logger)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	mailerMailer := mailer.NewMailer(viperViper)
	serviceService := service.NewService(transaction, logger, sidSid, jwt, mailerMailer, viperViper)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := user.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	batchRepository := repository.NewBatchRepository(repositoryRepository)
	batchService := batch.NewBatchService(serviceService, userRepository, batchRepository)
	batchHandler := handler.NewBatchHandler(handlerHandler, batchService)
	teamRepository := repository.NewTeamRepository(repositoryRepository)
	teamService := team.NewTeamService(teamRepository, serviceService)
	teamHandler := handler.NewTeamHandler(handlerHandler, teamService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwt, userHandler, batchHandler, teamHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewBatchRepository, repository.NewTeamRepository)

var serviceSet = wire.NewSet(service.NewService, user.NewUserService, batch.NewBatchService, team.NewTeamService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewBatchHandler, handler.NewTeamHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob, server.NewTask)

// build App
func newApp(httpServer *http.Server, job *server.Job) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
