// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User module"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponse"
                        }
                    }
                }
            }
        },
        "/students/register": {
            "post": {
                "description": "To register user account to the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User module"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response"
                        }
                    }
                }
            }
        },
        "/students/request-register": {
            "post": {
                "description": "To get the user info from the vendor and cache it",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User module"
                ],
                "summary": "User request-register",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.ReqRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response"
                        }
                    }
                }
            }
        },
        "/students/verify-email": {
            "post": {
                "description": "Confirms the email and sends the pre-saved cache student data got from IIUC server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User module"
                ],
                "summary": "User email verification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email confirmation token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response"
                        }
                    }
                }
            }
        },
        "/user": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User module"
                ],
                "summary": "Update user information",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/{uniId}/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieves the profile information of a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User module"
                ],
                "summary": "Get user information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "University ID",
                        "name": "uniId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "universityId"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "universityId": {
                    "type": "string",
                    "example": "c183074"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponseData": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.RegisterRequest": {
            "type": "object",
            "required": [
                "mobile",
                "name",
                "password",
                "section"
            ],
            "properties": {
                "alternateMobile": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "123456"
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.ReqRegister": {
            "type": "object",
            "required": [
                "universityId"
            ],
            "properties": {
                "universityId": {
                    "type": "string",
                    "example": "c183074"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StudentInfo": {
            "type": "object",
            "properties": {
                "alternateMobile": {
                    "type": "string"
                },
                "batch": {
                    "type": "integer"
                },
                "cgpa": {
                    "type": "number"
                },
                "completedCredits": {
                    "type": "integer"
                },
                "country": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                },
                "universityId": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StuffInfo": {
            "type": "object",
            "properties": {
                "alternateMobile": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.TeacherInfo": {
            "type": "object",
            "properties": {
                "alternateMobile": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "designation": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserResponseData": {
            "type": "object",
            "properties": {
                "changePass": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "isVerified": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "student": {
                    "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StudentInfo"
                },
                "stuff": {
                    "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StuffInfo"
                },
                "teacher": {
                    "$ref": "#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.TeacherInfo"
                },
                "universityId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "TMS server cmd",
	Description:      "Command to run the server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
