definitions:
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.BatchInfo:
    properties:
      closed:
        type: boolean
      createdAt:
        type: string
      createdBy:
        $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserInfo'
      defenceAt:
        type: string
      id:
        type: integer
      maxTeacherPref:
        type: integer
      maxTeamMember:
        type: integer
      minCGPARequired:
        type: number
      minCHRequired:
        type: integer
      name:
        type: string
      preDefenceAt:
        type: string
      quota:
        type: string
      teamRegDeadline:
        type: string
      updatedAt:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.BatchResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.BatchInfo'
      message:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.CreateBatchRequest:
    properties:
      defenceAt:
        type: string
      maxTeacherPref:
        type: integer
      maxTeamMember:
        type: integer
      minCGPARequired:
        type: number
      minCHRequired:
        type: integer
      name:
        type: string
      preDefenceAt:
        type: string
      quota:
        type: string
      teamRegDeadline:
        type: string
    required:
    - defenceAt
    - maxTeacherPref
    - maxTeamMember
    - minCHRequired
    - name
    - preDefenceAt
    - teamRegDeadline
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginRequest:
    properties:
      password:
        example: "123456"
        type: string
      universityId:
        example: c183074
        type: string
    required:
    - password
    - universityId
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponseData'
      message:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponseData:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.RegisterRequest:
    properties:
      alternateMobile:
        type: string
      mobile:
        type: string
      name:
        type: string
      password:
        example: "123456"
        minLength: 6
        type: string
      section:
        type: string
    required:
    - mobile
    - name
    - password
    - section
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.ReqRegister:
    properties:
      universityId:
        example: c183074
        type: string
    required:
    - universityId
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StudentInfo:
    properties:
      alternateMobile:
        type: string
      batch:
        type: integer
      cgpa:
        type: number
      completedCredits:
        type: integer
      country:
        type: string
      department:
        type: string
      email:
        type: string
      fullName:
        type: string
      gender:
        type: string
      mobile:
        type: string
      section:
        type: string
      universityId:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StuffInfo:
    properties:
      alternateMobile:
        type: string
      department:
        type: string
      fullName:
        type: string
      mobile:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.TeacherInfo:
    properties:
      alternateMobile:
        type: string
      department:
        type: string
      designation:
        type: string
      fullName:
        type: string
      mobile:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UpdateBatchRequest:
    properties:
      defenceAt:
        type: string
      maxTeacherPref:
        type: integer
      maxTeamMember:
        type: integer
      minCGPARequired:
        type: number
      minCHRequired:
        type: integer
      name:
        type: string
      preDefenceAt:
        type: string
      quota:
        type: string
      teamRegDeadline:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserInfo:
    properties:
      changePass:
        type: boolean
      email:
        type: string
      gender:
        type: string
      isAdmin:
        type: boolean
      isVerified:
        type: boolean
      role:
        type: string
      student:
        $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StudentInfo'
      stuff:
        $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.StuffInfo'
      teacher:
        $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.TeacherInfo'
      universityId:
        type: string
    type: object
  github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserInfo'
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Command to run the server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TMS server cmd
  version: 0.0.1
paths:
  /batch:
    get:
      consumes:
      - application/json
      description: Retrieves a list of batches with optional pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of records per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Get list of batches
      tags:
      - Batch module
    post:
      consumes:
      - application/json
      description: Creates a new batch
      parameters:
      - description: Batch creation details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.CreateBatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Create a new batch
      tags:
      - Batch module
  /batch/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an existing batch
      parameters:
      - description: Batch ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Delete batch
      tags:
      - Batch module
    get:
      consumes:
      - application/json
      description: Retrieves details of a batch
      parameters:
      - description: Batch ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.BatchResponse'
      summary: Get batch details
      tags:
      - Batch module
    put:
      consumes:
      - application/json
      description: Updates an existing batch
      parameters:
      - description: Batch ID
        in: path
        name: id
        required: true
        type: integer
      - description: Batch update details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UpdateBatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Update batch details
      tags:
      - Batch module
  /batch/{id}/close:
    put:
      consumes:
      - application/json
      description: Closes a batch
      parameters:
      - description: Batch ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Close a batch
      tags:
      - Batch module
  /batch/{id}/register:
    post:
      consumes:
      - application/json
      description: Registers the user to a batch
      parameters:
      - description: Batch ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Register to a batch
      tags:
      - Batch module
  /batch/{id}/registers:
    get:
      consumes:
      - application/json
      description: Retrieves a list of students registered to a batch
      parameters:
      - description: Batch ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Get list of students registered to a batch
      tags:
      - Batch module
  /batch/open:
    get:
      consumes:
      - application/json
      description: Retrieves a list of open batches
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: Get list of open batches
      tags:
      - Batch module
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.LoginResponse'
      summary: User login
      tags:
      - User module
  /students/register:
    post:
      consumes:
      - application/json
      description: To register user account to the system
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: User registration
      tags:
      - User module
  /students/request-register:
    post:
      consumes:
      - application/json
      description: To get the user info from the vendor and cache it
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.ReqRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: User request-register
      tags:
      - User module
  /students/verify-email:
    post:
      consumes:
      - application/json
      description: Confirms the email and sends the pre-saved cache student data got
        from IIUC server
      parameters:
      - description: Email confirmation token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      summary: User email verification
      tags:
      - User module
  /user:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: Update user information
      tags:
      - User module
  /users/{uni_id}/profile:
    get:
      consumes:
      - application/json
      description: Retrieves the profile information of a user
      parameters:
      - description: University ID
        in: path
        name: uni_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Imtiaz246_Thesis-Management-System_internal_apis_v1.Response'
      security:
      - Bearer: []
      summary: Get user information
      tags:
      - User module
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
